<%@ Page Inherits="Microsoft.SharePoint.Publishing.TemplateRedirectionPage,Microsoft.SharePoint.Publishing,Version=16.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c" %> <%@ Reference VirtualPath="~TemplatePageUrl" %> <%@ Reference VirtualPath="~masterurl/custom.master" %><%@ Register Tagprefix="SharePoint" Namespace="Microsoft.SharePoint.WebControls" Assembly="Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<html xmlns:mso="urn:schemas-microsoft-com:office:office" xmlns:msdt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"><head>
<!--[if gte mso 9]><SharePoint:CTFieldRefs runat=server Prefix="mso:" FieldList="FileLeafRef,Comments,PublishingPreviewImage,PublishingHidden,_PublishingMigratedGuid,PublishingAssociatedContentType,PublishingAssociatedVariations"><xml>
<mso:CustomDocumentProperties>
<mso:PublishingContact msdt:dt="string">9</mso:PublishingContact>
<mso:PublishingIsFurlPage msdt:dt="string">0</mso:PublishingIsFurlPage>
<mso:display_urn_x003a_schemas-microsoft-com_x003a_office_x003a_office_x0023_PublishingContact msdt:dt="string">MOD Administrator</mso:display_urn_x003a_schemas-microsoft-com_x003a_office_x003a_office_x0023_PublishingContact>
<mso:PublishingContactPicture msdt:dt="string"></mso:PublishingContactPicture>
<mso:RobotsNoIndex msdt:dt="string">0</mso:RobotsNoIndex>
<mso:PublishingContactName msdt:dt="string"></mso:PublishingContactName>
<mso:ContentTypeId msdt:dt="string">0x01010007FF3E057FA8AB4AA42FCB67B453FFC100289DA909FAC009468E32DB107000873D</mso:ContentTypeId>
<mso:PublishingPageLayoutName msdt:dt="string">DepartmentLayout.aspx</mso:PublishingPageLayoutName>
<mso:Comments msdt:dt="string"></mso:Comments>
<mso:PublishingContactEmail msdt:dt="string"></mso:PublishingContactEmail>
<mso:PublishingPageLayout msdt:dt="string">https://mod223137.sharepoint.com/sites/NewCoxOne/_catalogs/masterpage/coxone/DepartmentLayout.aspx, /sites/NewCoxOne/_catalogs/masterpage/coxone/DepartmentLayout.aspx</mso:PublishingPageLayout>
<mso:PublishingHidden msdt:dt="string">0</mso:PublishingHidden>
<mso:PublishingPageContent msdt:dt="string">&lt;p&gt;​&lt;/p&gt;&lt;p style=&quot;text-align&amp;#58;left;&quot;&gt;&lt;span&gt;&lt;/span&gt;Lorem &lt;img class=&quot;ms-rtePosition-2&quot; src=&quot;/sites/NewCoxOne/PublishingImages/Banners/resourcesimg1.jpg&quot; alt=&quot;&quot; style=&quot;margin&amp;#58;5px;width&amp;#58;201px;&quot; /&gt;ipsum dolor sit amet, us neque ridicuTestlus sit &lt;strong&gt;augue, laoreet vitae &lt;/strong&gt;nam, nunc lacnisl aliquam dui proin vestibulum fringilla. Mollis condimentum, interdum sit integer id ante augue cumque. Curabitur varius varius. Aptent curabitur &lt;/p&gt;&lt;p style=&quot;text-align&amp;#58;left;&quot;&gt;&lt;strong&gt;vivamus vivamus sapien &lt;/strong&gt;&lt;strong&gt;e&lt;/strong&gt;&lt;strong&gt;u&lt;/strong&gt;, purus suspendisse eros maecenas ac, pharetra fringilla nostra quam semper, arcu molestie elit taciti nulla pharetra. Donec consequat urna morbi mattis tempor, feugiat mauris sit nam massa integer. &lt;/p&gt;&lt;p style=&quot;text-align&amp;#58;left;&quot;&gt;&lt;img class=&quot;ms-rtePosition-1&quot; src=&quot;/sites/NewCoxOne/PublishingImages/News%20Article/items-7.jpg&quot; alt=&quot;&quot; style=&quot;margin&amp;#58;5px;width&amp;#58;202px;&quot; /&gt;&lt;/p&gt;&lt;p style=&quot;text-align&amp;#58;left;&quot;&gt;. &lt;/p&gt;&lt;p style=&quot;text-align&amp;#58;left;&quot;&gt;.&lt;/p&gt;&lt;p style=&quot;text-align&amp;#58;left;&quot;&gt;Justo sed eget donec, convallis vestibulum orci&amp;#160;duis porta, dui nonummy magna, turpis quisque porttitor porta erat donec. &lt;/p&gt;&lt;p style=&quot;text-align&amp;#58;left;&quot;&gt;&lt;strong&gt;Suspendisse risus vitae rutrum, tristique risus&amp;#160;aptent.&lt;/strong&gt; Lacus vel porttitor aliquam quisque. Purus ultrices nascetur, wisi enim aptent tellus, vulputate. Tellus vitae habitasse mi, dolor blandit risus ante leo eget, faucibus velit a vel sit​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​&lt;/p&gt;</mso:PublishingPageContent>
<mso:PublishingImageCaption msdt:dt="string">&lt;p&gt;​&lt;/p&gt;&lt;p&gt;&lt;span&gt;&lt;/span&gt;​&lt;img class=&quot;ms-rtePosition-1&quot; src=&quot;/sites/NewCoxOne/PublishingImages/News%20Article/Leadership-Vision-Section.png&quot; alt=&quot;&quot; style=&quot;margin&amp;#58;5px;&quot; /&gt;Mauris nascetur volutpat sed arcu tellus, lectus laoreet donec, suspendisse lacus libero platea nonummy nulla. Sem vel labore diam, orci ccondimentum orci at neque Suspendisse dignissim nibhurabitur adipiscing vitae. Pulvinar vehicula tristique. .&lt;/p&gt;&lt;p&gt;Montes sed ad pretium, consectetuer vestibulum quisque quis lorem vehicula, id donec eu etiam augue at, pede praesent vel eros. Dignissim arcu id. &lt;strong&gt;Sollicitudin est erat sed mauris,&lt;/strong&gt; nullam pellentesque interdum dolor, massa commodo. Posuere id proin nec lacus pellentesque, erat fusce. &lt;/p&gt;&lt;p&gt;&lt;strong&gt;Magna habitasse nulla urna consequat sit sem mattis.&amp;#160;&lt;/strong&gt; Turpis, sem maecenas pellentesque, sagittis pulvinar sit quisque libero dignissim. Justo nihil gravida aliquam. Pharetra eu blandit netus, mauris suscipit pede vestibulum nec, commodo sit inceptos ut rhoncus interdum purus, diam luctus,.&lt;/p&gt;&lt;font color=&quot;#000000&quot; face=&quot;Times New Roman&quot; size=&quot;3&quot;&gt;&lt;/font&gt;&lt;p style=&quot;margin&amp;#58;0in 0in 8pt;text-align&amp;#58;right;&quot;&gt;&lt;font class=&quot;ms-rteThemeForeColor-5-4&quot; face=&quot;Calibri&quot; size=&quot;3&quot;&gt;View Human Resources Organizational Chart&lt;span&gt;&lt;/span&gt;&lt;/font&gt;&lt;/p&gt;</mso:PublishingImageCaption>
<mso:RequiresRouting msdt:dt="string">False</mso:RequiresRouting>
<mso:PublishingPreviewImage msdt:dt="string"></mso:PublishingPreviewImage>
<mso:PublishingAssociatedVariations msdt:dt="string"></mso:PublishingAssociatedVariations>
<mso:PublishingAssociatedContentType msdt:dt="string">;#Administrative Task;#0x010802;#</mso:PublishingAssociatedContentType>
</mso:CustomDocumentProperties>
</xml></SharePoint:CTFieldRefs><![endif]-->
<title>Human Resources</title></head>